In [ ]:
# ---------------------------   CALL ELEMENTES

In [41]:
a=np.array([[21,24,14,100],[37,14,18,200]])
a

array([[ 21,  24,  14, 100],
       [ 37,  14,  18, 200]])

In [34]:
a[0][1]

24

In [35]:
a[:1,:]

array([[ 21,  24,  14, 100]])

In [37]:
a[:,1:2]

array([[24],
       [14]])

In [40]:
a[0]

array([ 21,  24,  14, 100])

In [43]:
#------------------------------------ ONES, ZEROS, RAMDOM, ARANGE

In [45]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [52]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
np.random.random((3,5))

array([[0.70466652, 0.26276331, 0.02047234, 0.52460934, 0.94329815],
       [0.50440034, 0.7239841 , 0.7150583 , 0.21524823, 0.60397202],
       [0.77900416, 0.43720182, 0.66467344, 0.54410007, 0.38612041]])

In [75]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
# --------------------------------------listas 

In [70]:
list(range(0,5,2))

[0, 2, 4]

In [80]:
# ---------------------------------- operaciones con dataframes

In [102]:
a

array([[2, 3, 5],
       [5, 1, 2]])

In [103]:
b=a*2
b

array([[ 4,  6, 10],
       [10,  2,  4]])

In [104]:
suma=a+b
suma

array([[ 6,  9, 15],
       [15,  3,  6]])

In [105]:
producto=a*b
producto

array([[ 8, 18, 50],
       [50,  2,  8]])

In [106]:
producto.sum()

136

In [91]:
#------------------------------- multiplicacion de matrices

In [97]:
a=np.array([[2,3,5],[5,1,2]])
b=np.array([[1,2],[1,7],[1,5]])

In [98]:
a,b

(array([[2, 3, 5],
        [5, 1, 2]]),
 array([[1, 2],
        [1, 7],
        [1, 5]]))

In [99]:
np.dot(a,b)

array([[10, 50],
       [ 8, 27]])