Numpy

In [2]:
import numpy as np


In [3]:
a=np.array([1.3,2.6,3.4])
a

array([1.3, 2.6, 3.4])

In [4]:
type(a)


numpy.ndarray

In [5]:
a.dtype


dtype('float64')

In [6]:
a.size

3

In [7]:
len(a)

3

In [8]:
a.shape

(3,)

Imprimir el array

In [9]:
for e in a:
  print(e)

1.3
2.6
3.4


In [10]:
b=np.array([[3,4,5],[9,2,1]])
b

array([[3, 4, 5],
       [9, 2, 1]])

In [11]:
b[0]

array([3, 4, 5])

In [12]:
b[0][1]

4

In [13]:
b.shape

(2, 3)

In [14]:
b.dtype

dtype('int64')

In [15]:
f=np.array([[1,2],[4,5]],dtype=np.float32)
f

array([[1., 2.],
       [4., 5.]], dtype=float32)

In [16]:
f.dtype

dtype('float32')

In [17]:
f[0],f[1]

(array([1., 2.], dtype=float32), array([4., 5.], dtype=float32))

In [18]:
f[0][0]

1.0

In [19]:
f[:][:]

array([[1., 2.],
       [4., 5.]], dtype=float32)

Desafío : Mostrar los datos de la columna 1

In [20]:
f[:,1:2]

array([[2.],
       [5.]], dtype=float32)

Recorrido por filas

In [21]:
for e1 in f:
  print(e1)

[1. 2.]
[4. 5.]


In [22]:
for e1 in f:
  #print(e1)
  for e2 in e1:
    print(e2)


1.0
2.0
4.0
5.0


Desafío: Recorrido por columnas

In [24]:
for e1 in f:

    for e2 in e1:

        print(e2, end=" ")

    print()

1.0 2.0 
4.0 5.0 


Creación de arreglos con valores

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.random((2,2))

array([[0.46478703, 0.91791328],
       [0.40888478, 0.99238058]])

Operaciones con array

In [28]:
m=np.array([4,2,7,1])
m

array([4, 2, 7, 1])

In [29]:
n=4*m
n

array([16,  8, 28,  4])

In [ ]:
suma=m+n
suma

array([20, 10, 35,  5])

In [30]:
p=np.array([1,1,1])
p

array([1, 1, 1])

In [33]:
# No haga este en casa
#suma1=m+p
#suma1

In [35]:
m,n

(array([4, 2, 7, 1]), array([16,  8, 28,  4]))

In [ ]:
producto=m*n
producto

array([ 64,  16, 196,   4])

Producto de matrices

In [36]:
m1=np.array([[4,5],[6,7]])
m1

array([[4, 5],
       [6, 7]])

In [37]:
m2=np.ones((2,2))
m2

array([[1., 1.],
       [1., 1.]])

In [38]:
s=m1*m2
s

array([[4., 5.],
       [6., 7.]])

In [39]:
np.dot(m1,m2)


array([[ 9.,  9.],
       [13., 13.]])

Funciones de arrays

In [40]:
m1

array([[4, 5],
       [6, 7]])

In [41]:
m1.max()

7

In [42]:
m1.sum()

22

In [43]:
m1[:,1]

array([5, 7])

In [44]:
m1.mean()

5.5