Numpy

In [ ]:
import numpy as np


In [ ]:
a=np.array([1.3,2.6,3.4])
a

array([1.3, 2.6, 3.4])

In [ ]:
type(a)


numpy.ndarray

In [ ]:
a.dtype


dtype('float64')

In [ ]:
a.size

3

In [ ]:
len(a)

3

In [ ]:
a.shape

(3,)

In [ ]:
b=np.array([[3,4,5],[9,2,1]])
b

array([[3, 4, 5],
       [9, 2, 1]])

In [ ]:
b.shape

(2, 3)

In [ ]:
f=np.array([[1,2],[4,5]],dtype=np.float32)
f

array([[1., 2.],
       [4., 5.]], dtype=float32)

In [ ]:
f[0],f[1]

(array([1., 2.], dtype=float32), array([4., 5.], dtype=float32))

In [ ]:
f[0][0]

1.0

Desafío : Mostrar los datos de la columna 1

In [ ]:
f[:,:1]

array([[1.],
       [4.]], dtype=float32)

Recorrido por filas

In [ ]:
for e1 in f:
  #print(e1)
  for e2 in e1:
    print(e2)


1.0
2.0
4.0
5.0


Desafío: Recorrido por columnas

Creación de arreglos con valores

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.random((2,2))

array([[0.46478703, 0.91791328],
       [0.40888478, 0.99238058]])

Operaciones con array

In [ ]:
m=np.array([4,2,7,1])
m

array([4, 2, 7, 1])

In [ ]:
n=4*m
n

array([16,  8, 28,  4])

In [ ]:
suma=m+n
suma

array([20, 10, 35,  5])

In [ ]:
producto=m*n
producto

array([ 64,  16, 196,   4])

Producto de matrices

In [ ]:
m1=np.array([[4,5],[6,7]])
m1

array([[4, 5],
       [6, 7]])

In [ ]:
m2=np.ones((2,2))
m2

array([[1., 1.],
       [1., 1.]])

In [ ]:
s=m1*m2
s

array([[4., 5.],
       [6., 7.]])

In [ ]:
np.dot(m1,m2)


array([[ 9.,  9.],
       [13., 13.]])

Funciones de arrays

In [ ]:
m1

array([[4, 5],
       [6, 7]])

In [ ]:
m1.sum()

22

In [ ]:
m1[:,1]

array([5, 7])